name: golangci-lint
on: [pull_request]
jobs:
  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Grant private package access
        run: |
          git config --global url."https://${{ secrets.GLOBAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/Bidroombv".insteadOf "https://github.com/Bidroombv"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
